[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jalec", email = "jordi.alejandre10@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ecdsa>=0.19.2",
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
server = "server:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
